config/routes.rb
Rails.application.routes.draw do

  get 'search/search'
  get 'search/search_page'
  namespace :admin do
    resources :members, only: [:index,:show, :edit, :update]
    get 'members/:id/comments' =>'members#comments', as: 'member_comments'
    get 'members/:id/games' =>'members#games', as: 'member_games'
    get 'members/:id/game_reports' =>'members#game_reports', as: 'member_game_reports'
    get 'members/:id/comment_reports' =>'members#comment_reports', as: 'member_comment_reports'
    resources :genres, only: [:index,:create, :update]
    resources :games, only: [:index,:show, :edit, :update,:destroy]
    resources :comments, only: [:destroy]
    resources :models, only: [:index,:create, :update]
    resources :game_reports, only: [:index,:show, :update]
    resources :comment_reports, only: [:index,:show, :update]
    resources :contacts, only: [:edit, :update, :index]
    post 'contacts/status_update' =>'contacts#status_update', as: 'contact_status_update'
    resources :warning_mails, only: [:new, :create, :show,:index]
    get 'search/search'
    get 'search/search_page'
  end
  get 'admin/top' => 'admin#top', as: 'admin_top'
  devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
  }
  devise_for :members, controllers: {
  		sessions:      'members/sessions',
      passwords:     'members/passwords',
      registrations: 'members/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#top'
  get 'home/about' => 'home#about'

  resources :members, only: [:show, :edit, :update]
  get 'members/:id/delete_me' => 'members#delete_me', as: 'delete_me'
  put 'members/:id/delete_me' =>'members#withdraw', as: 'withdraw'
  get 'members/:id/comments' =>'members#comments', as: 'my_comments'
  get 'members/:id/games' =>'members#games', as: 'my_games'
  get 'members/:id/favorites' =>'members#favorites', as: 'my_favorites'
  resources :game_reports, only: [:new, :create,:show]
  resources :comment_reports, only: [:new, :create,:show]
  resources :contacts, only: [:new, :create]

  resources :games, only: [:index, :show, :edit, :update, :create,:new] do
    resource :comments, only: [:create,:destroy]
    resource :favorites, only: [:create,:destroy]
  end
  put 'games/:id/hidden'      => 'games#hidden'     , as: 'hidden'
  post 'games/:id/playtime_create'      => 'games#playtime_create'
  get 'home/ranking' =>'home#ranking', as: 'ranking'


end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :member
  belongs_to :game

  has_many :comment_reports, dependent: :destroy

  validates :comment, presence: true

end

app/models/comment_report.rb
class CommentReport < ApplicationRecord
  belongs_to :comment

  enum reason:{
    "その他の理由": 0,
    "コメントの情報に間違いがあります": 1,
    "コメントに不適切な表現があります": 2,
    "このコメントは特定の人・物を批判しています": 3,
  }
  enum status:{
    "未対応": 0,
    "対応中": 1,
    "保留中": 2,
    "対応済み": 3
  }

  validates :report, presence: true
  validates :reason, presence: true

end

app/models/contact.rb
class Contact < ApplicationRecord
  enum status:{
    "未対応": 0,
    "対応中": 1,
    "保留中": 2,
    "対応済み": 3
  }

  validates :contact_text, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true,format: { with: VALID_EMAIL_REGEX }
  validates :name, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :member
  belongs_to :game
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :genre
  belongs_to :member

  has_many :playtimes, dependent: :destroy
  accepts_nested_attributes_for :playtimes

  has_many :game_models
  has_many :models, dependent: :destroy,through: :game_models
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :game_reports, dependent: :destroy

  enum cero_rating:{"A(全年齢)": 0,"B(12歳以上)": 1,"C(15歳以上)": 2,"D(17歳以上)": 3,"Z(18歳以上)": 4}

  validates :title, presence: true
  validates :release, presence: true
  validates :number_of_people, presence: true
  validates :text, presence: true
  validates :complete, inclusion: { in: [true, false] }
  validates :orbit, inclusion: { in: [true, false] }
  validates :multi_ending, inclusion: { in: [true, false] }
  validates :cero_rating, presence: true
  validates :model_ids, presence: true

  # プレイ時間の追加済みか
  def playtime_by?(member)
   playtimes.where(member_id: member.id).exists?
  end
  # お気に入り済みか
  def favorite_by?(member)
   favorites.where(member_id: member.id).exists?
  end
end

app/models/game_model.rb
class GameModel < ApplicationRecord
  belongs_to :game
  belongs_to :model

end

app/models/game_report.rb
class GameReport < ApplicationRecord
  belongs_to :game

  enum reason:{
    "その他の理由": 0,
    "記事内のデータに間違いがあります": 1,
    "記事内に不適切な表現があります": 2,
    "この記事は特定の人・物を批判しています": 3,
    "同じゲームの記事が存在しています": 4
  }
  enum status:{
    "未対応": 0,
    "対応中": 1,
    "保留中": 2,
    "対応済み": 3
  }

  validates :report, presence: true
  validates :reason, presence: true

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :games #ジャンル消してもゲームは消さないのでdestroyは無し

  validates :name, presence: true

end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum status: {有効: 0, 退会: 1,停止: 2}

  has_many :games #会員を消してもゲームは消さないのでdestroyは無し
  has_many :playtimes #同上
  has_many :comments, dependent: :destroy #コメントは消す
  has_many :favorites, dependent: :destroy #同上
  has_many :warning_mails, dependent: :destroy #同上

  validates :name, presence: true
end

app/models/model.rb
class Model < ApplicationRecord
  has_many :game_models
  has_many :games, dependent: :destroy,through: :game_models

  validates :model, presence: true

end

app/models/playtime.rb
class Playtime < ApplicationRecord
  belongs_to :game
  belongs_to :member

  enum time:{
    "30分未満": 30,
    "30分~1時間": 60,
    "1時間~1時間30分": 90,
    "1時間30分~2時間": 120,
    "2時間~2時間30分": 150,
    "2時間30分~3時間": 180,
    "3時間~3時間30分": 210,
    "3時間30分~4時間": 240,
    "4時間~4時間30分": 270,
    "4時間30分~5時間": 300,
    "5時間~5時間30分": 330,
    "5時間30分~6時間": 360,
    "6時間~6時間30分": 390,
    "6時間30分~7時間": 420,
    "7時間~7時間30分": 450,
    "7時間30分~8時間": 480,
    "8時間~8時間30分": 510,
    "8時間30分~9時間": 540,
    "9時間~9時間30分": 570,
    "9時間30分~10時間": 600,
    "10時間~20時間": 1200,
    "20時間~30時間": 1800,
    "30時間~40時間": 2400,
    "40時間~50時間": 3000,
    "50時間~60時間": 3600,
    "60時間~70時間": 4200,
    "70時間~80時間": 4800,
    "80時間~90時間": 5400,
    "90時間~100時間": 6000,
    "100時間~150時間": 9000,
    "150時間~200時間": 12000,
    "200時間~250時間": 15000,
    "250時間~300時間": 18000,
    "300時間以上":0
  }

  validates :time, presence: true

end

app/models/warning_mail.rb
class WarningMail < ApplicationRecord
  belongs_to :member
  validates :warning_text, presence: true
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admin/top.html.erb
<%= flash[:notice] %>

<div class="row">
  <div class="col-xs-12">
    <h2 class="page-title text-center">未対応の通報、問い合わせ</h2>
  </div>
</div>

<div class="row">
  <div class="col-xs-4">
    <h3 class="text-center" id="game-report">ゲーム記事通報<%= @game_reports.count %>件</h3>

    <div class="report">
      <table class= "table table-hover table-bordered table-admin">
        <thead>
          <tr>
            <th class="text-center">通報日時</th>
            <th class="text-center">通報内容</th>
          </tr>
        </thead>
        <tbody>
          <% @game_reports.each do |game| %>
            <tr class="text-center table-cel">
              <td><%= link_to admin_game_report_path(game.id) do %><%= game.created_at.strftime("%y/%m/%d %H:%M") %><% end %></td>
              <td><%= game.reason %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="col-xs-4">
    <h3 class="text-center" id="comment-report">コメント通報<%= @comment_reports.count %>件</h3>

    <div class="report">
      <table class= "table table-hover table-bordered table-admin">
        <thead>
          <tr>
            <th class="text-center">通報日時</th>
            <th class="text-center">通報内容</th>
          </tr>
        </thead>
        <tbody>
          <% @comment_reports.each do |comment| %>
            <tr class="text-center table-cel">
              <td><%= link_to admin_comment_report_path(comment.id) do %><%= comment.created_at.strftime("%y/%m/%d %H:%M") %><% end %></td>
              <td><%= comment.reason %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

  <div class="col-xs-4">
    <h3 class="text-center" id="comment-report">問い合わせ<%= @contacts.count %>件</h3>

    <div class="report">
      <table class= "table table-hover table-bordered table-admin">
        <thead>
          <tr>
            <th class="text-center">問い合わせ日時</th>
            <th class="text-center">問い合わせ内容</th>
          </tr>
        </thead>
        <tbody>
          <% @contacts.each do |contact| %>
            <tr class="text-center table-cel">
              <td><%= link_to edit_admin_contact_path(contact.id) do %><%= contact.created_at.strftime("%y/%m/%d %H:%M") %><% end %></td>
              <td><%= contact.contact_text.truncate(10, separator: /\s/) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>