config/routes.rb
Rails.application.routes.draw do

  get 'search/search'
  get 'search/search_page'
  namespace :admin do
    resources :members, only: [:index,:show, :edit, :update]
    get 'members/:id/comments' =>'members#comments', as: 'member_comments'
    get 'members/:id/games' =>'members#games', as: 'member_games'
    get 'members/:id/game_reports' =>'members#game_reports', as: 'member_game_reports'
    get 'members/:id/comment_reports' =>'members#comment_reports', as: 'member_comment_reports'
    resources :genres, only: [:index,:create, :update]
    resources :games, only: [:index,:show, :edit, :update,:destroy]
    resources :comments, only: [:destroy]
    resources :models, only: [:index,:create, :update]
    resources :game_reports, only: [:index,:show, :update]
    resources :comment_reports, only: [:index,:show, :update]
    resources :contacts, only: [:edit, :update, :index]
    post 'contacts/status_update' =>'contacts#status_update', as: 'contact_status_update'
    resources :warning_mails, only: [:new, :create, :show,:index]
    get 'search/search'
    get 'search/search_page'
  end
  get 'admin/top' => 'admin#top', as: 'admin_top'
  devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
  }
  devise_for :members, controllers: {
  		sessions:      'members/sessions',
      passwords:     'members/passwords',
      registrations: 'members/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#top'
  get 'home/about' => 'home#about'

  resources :members, only: [:show, :edit, :update]
  get 'members/:id/delete_me' => 'members#delete_me', as: 'delete_me'
  put 'members/:id/delete_me' =>'members#withdraw', as: 'withdraw'
  get 'members/:id/comments' =>'members#comments', as: 'my_comments'
  get 'members/:id/games' =>'members#games', as: 'my_games'
  get 'members/:id/favorites' =>'members#favorites', as: 'my_favorites'
  resources :game_reports, only: [:new, :create,:show]
  resources :comment_reports, only: [:new, :create,:show]
  resources :contacts, only: [:new, :create]

  resources :games, only: [:index, :show, :edit, :update, :create,:new] do
    resource :comments, only: [:create,:destroy]
    resource :favorites, only: [:create,:destroy]
  end
  put 'games/:id/hidden'      => 'games#hidden'     , as: 'hidden'
  post 'games/:id/playtime_create'      => 'games#playtime_create'
  get 'home/ranking' =>'home#ranking', as: 'ranking'


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @genres = Genre.where(status: 'ture').reverse_order

    @newgames = Game.where(status: true).reverse_order.limit(5) #新着5件取得

    day = Date.current #今日
    mon = day << 1 #ひと月前からのデータ
    @rankgames = Game.select('games.*','count(favorites.id) AS favs') #gameテーブルの情報とfavoriteの数を取得
                  .left_joins(:favorites) #favoritesを右側(gamesが左側)のテーブルにして結合
                  .group('games.id') #game.idでグループ
                  .where(created_at: mon..Time.now) #閲覧日から一ヶ月前までを集計
                  .order('favs desc') #favorite数の多い順に並べ替え
                  .limit(5) #5件まで
                  .where(status: true)
  end

  def ranking
    day = Date.today #今日
    mon = day << 1 #ひと月前からのデータ
    @games = Game.select('games.*','count(favorites.id) AS favs') #gameテーブルの情報とfavoriteの数を取得
                  .left_joins(:favorites) #favoritesを右側(gamesが左側)のテーブルにして結合
                  .group('games.id') #game.idでグループ
                  .where(created_at: mon..Time.now) #閲覧日から一ヶ月前までを集計
                  .page(params[:page]).per(10) #ページネーション
                  .order('favs desc') #favorite数の多い順に並べ替え
                  .where(status: true)
  end

  def about
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/about.html.erb
<h2 class="text-center page-title">GIME GIMMEについて</h2>

<h4 class="text-center">GIMEはTIMEとGAMEを合わせた造語です。<br>
そしてGIMMEは貪欲に求めるという意味です。<br>
<br>
GIME GIMMEは、ゲームが好きでも忙しくて時間が足りない。<br>
それでも自分好みのゲームをたくさんやってみたい。<br>
そんな人の手助けができれば良いなと思って誕生した口コミサイトです。<br>
<br>
プレイした人がプレイ時間を投票することで、プレイ時間の目安が目で見えるので、<br>
GIME GIMEなあなたの手助けになればと思っています。</h4>

app/views/home/ranking.html.erb
<div class="row">
  <div class="col-xs-12">
      <h2 class="page-title">今月のランキング</h2>
      <% @games.each.with_index(1) do |game, i| %>
        <div class="index-game" id="search-game">
          <h3><span class="rank-num"><%= i %>. <%= link_to game.title,game_path(game.id) %></h3>
          <ul>
          <li>
            <span class="glyphicon glyphicon-heart"></span> <%= game.favorites.count %>
            <span class="glyphicon glyphicon-comment"></span> <%= game.comments.count %>
          </li>
          <li class="genre-item"><%= link_to game.genre.name,games_path(id: game.genre.id) %></li>
          <li class="index-date">作成日：<%= game.created_at.strftime("%Y年%m月%d日") %></li>
          </ul>
        </div>
      <% end %>
      <div class="text-center"><%= paginate @games %></div>
  </div>
</div>

app/views/home/top.html.erb
<%= flash[:notice] %>

<div class="row">
  <div class="col-xs-12">
    <div class="genre-box">
      <ul>
      <% @genres.each do |genre| %>
          <li class="genre-item"><%= link_to genre.name,games_path(id: genre.id) %></li>
      <% end %>
      </ul>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-xs-6">
    <div class="top-game-box">
      <div class="top-game-title">
        <h2 class="glyphicon glyphicon-bullhorn">新着記事</h2>
        <p><%= link_to "▶︎もっと見る",games_path %></p>
      </div>
      <% @newgames.each do |game| %>
        <div class="index-game">
          <h3><%= link_to game.title,game_path(game.id) %></h3>
          <ul>
          <li>
            <span class="glyphicon glyphicon-heart"></span> <%= game.favorites.count %>
            <span class="glyphicon glyphicon-comment"></span> <%= game.comments.count %>
          </li>
          <li class="genre-item"><%= link_to game.genre.name,games_path(id: game.genre.id) %></li>
          <li class="top-time"><%= time_ago_in_words(game.created_at) %>前</li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-xs-6">
    <div class="top-game-box">
      <div class="top-game-title">
      <h2  class="glyphicon glyphicon-bell">ランキング</h2>
      <p><%= link_to "▶︎もっと見る",ranking_path %></p>
      </div>
      <% @rankgames.each.with_index(1) do |game, i| %>
        <div class="index-game">
          <h3><span class="rank-num"><%= i %>. </span><%= link_to game.title,game_path(game.id) %></h3>
          <ul>
            <li>
              <span class="glyphicon glyphicon-heart"></span> <%= game.favorites.count %>
              <span class="glyphicon glyphicon-comment"></span> <%= game.comments.count %>
            </li>
            <li class="genre-item"><%= link_to game.genre.name,games_path(id: game.genre.id) %></li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>