config/routes.rb
Rails.application.routes.draw do

  get 'search/search'
  get 'search/search_page'
  namespace :admin do
    resources :members, only: [:index,:show, :edit, :update]
    get 'members/:id/comments' =>'members#comments', as: 'member_comments'
    get 'members/:id/games' =>'members#games', as: 'member_games'
    get 'members/:id/game_reports' =>'members#game_reports', as: 'member_game_reports'
    get 'members/:id/comment_reports' =>'members#comment_reports', as: 'member_comment_reports'
    resources :genres, only: [:index,:create, :update]
    resources :games, only: [:index,:show, :edit, :update,:destroy]
    resources :comments, only: [:destroy]
    resources :models, only: [:index,:create, :update]
    resources :game_reports, only: [:index,:show, :update]
    resources :comment_reports, only: [:index,:show, :update]
    resources :contacts, only: [:edit, :update, :index]
    post 'contacts/status_update' =>'contacts#status_update', as: 'contact_status_update'
    resources :warning_mails, only: [:new, :create, :show,:index]
    get 'search/search'
    get 'search/search_page'
  end
  get 'admin/top' => 'admin#top', as: 'admin_top'
  devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
  }
  devise_for :members, controllers: {
  		sessions:      'members/sessions',
      passwords:     'members/passwords',
      registrations: 'members/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#top'
  get 'home/about' => 'home#about'

  resources :members, only: [:show, :edit, :update]
  get 'members/:id/delete_me' => 'members#delete_me', as: 'delete_me'
  put 'members/:id/delete_me' =>'members#withdraw', as: 'withdraw'
  get 'members/:id/comments' =>'members#comments', as: 'my_comments'
  get 'members/:id/games' =>'members#games', as: 'my_games'
  get 'members/:id/favorites' =>'members#favorites', as: 'my_favorites'
  resources :game_reports, only: [:new, :create,:show]
  resources :comment_reports, only: [:new, :create,:show]
  resources :contacts, only: [:new, :create]

  resources :games, only: [:index, :show, :edit, :update, :create,:new] do
    resource :comments, only: [:create,:destroy]
    resource :favorites, only: [:create,:destroy]
  end
  put 'games/:id/hidden'      => 'games#hidden'     , as: 'hidden'
  post 'games/:id/playtime_create'      => 'games#playtime_create'
  get 'home/ranking' =>'home#ranking', as: 'ranking'


end

app/models/game_report.rb
class GameReport < ApplicationRecord
  belongs_to :game

  enum reason:{
    "その他の理由": 0,
    "記事内のデータに間違いがあります": 1,
    "記事内に不適切な表現があります": 2,
    "この記事は特定の人・物を批判しています": 3,
    "同じゲームの記事が存在しています": 4
  }
  enum status:{
    "未対応": 0,
    "対応中": 1,
    "保留中": 2,
    "対応済み": 3
  }

  validates :report, presence: true
  validates :reason, presence: true

end

app/controllers/admin/game_reports_controller.rb
class Admin::GameReportsController < AdminController
  def show
    @report = GameReport.find(params[:id])
    @game = Game.find_by(id: @report.game_id)
    @models = GameModel.where(game_id: @game.id)
  end

  def update
    report = GameReport.find(params[:id])
    report.update!(report_params)
    redirect_to admin_game_report_path(report.id)
  end

  def index
    @reports = GameReport.all.page(params[:page]).per(10).reverse_order
  end

  private
  def report_params
    params.require(:game_report).permit(:status,:correspondence)
  end
end

app/controllers/game_reports_controller.rb
class GameReportsController < ApplicationController
  def new
    @game = Game.find(params[:game_id])
    @models = GameModel.where(game_id: @game.id)
    @report = GameReport.new
  end

  def create
    @report = GameReport.new(report_params)
    if @report.save
      begin
        @game = Game.find_by!(id: @report.game_id)
        @models = GameModel.where(game_id: @game.id)
        member = Member.find_by!(id: @game.member_id)
        member.report_count = member.report_count + 1
        member.save!
      retry
      end
    else
      @game = Game.find_by(id: @report.game_id)
      @models = GameModel.where(game_id: @game.id)
      render :new
    end
  end

  private
  def report_params
    params.require(:game_report).permit(:reason,:report,:status,:correspondence,:game_id)
  end
end

app/helpers/admin/game_reports_helper.rb
module Admin::GameReportsHelper
end

app/helpers/game_reports_helper.rb
module GameReportsHelper
end

app/views/admin/game_reports/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h2 class="page-title" id="game-report">ゲーム記事通報一覧</h2>

    <div class="report">
      <table class= "table table-hover table-bordered table-admin">
        <thead>
          <tr>
            <th class="text-center">ゲームタイトル</th>
            <th class="text-center">作成者</th>
            <th class="text-center">通報日時</th>
            <th class="text-center">通報内容</th>
            <th class="text-center">ステータス</th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          <% @reports.each do |game| %>
            <tr class="text-center table-cel">
              <td><%= link_to game.game.title, admin_game_path(game.game.id) %></td>
              <td><%= link_to game.game.member.name,admin_member_path(game.game.member.id) %></td>
              <td><%= game.created_at.strftime("%y/%m/%d %H:%M") %></td>
              <td><%= game.reason %></td>
              <td><%= game.status %></td>
              <td><%= link_to "通報詳細",admin_game_report_path(game.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="text-center"><%= paginate @reports %></div>
  </div>
</div>

app/views/admin/game_reports/show.html.erb
<div class="row">
  <div class="col-xs-12">
    <h2 class="page-title">通報詳細</h2>
  </div>
</div>

<div class="game-report">
  <div class="row">
    <div class="col-xs-12">
      <div class="admin-game-report-table">
        <table>
          <caption><h4>通報ページ情報</h4></caption>
          <thead>
            <tr>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>タイトル</td>
              <td colspan="4"><%= link_to @game.title,admin_game_path(@game.id),class: "game-report-title" %>
                <%= link_to "編集する",edit_admin_game_path(@game.id),class: "btn btn-primary btn-sm" %>
              </td>
            </tr>
            <tr>
              <td>投稿者</td>
              <td colspan="4"><%= link_to @game.member.name,admin_member_path(@game.member.id) %>
              </td>
            </tr>
            <tr>
              <td>発売日</td>
              <td><%= @game.release.strftime("%Y年%m月%d日") %></td>
              <td></td>
              <td>コンプリート要素</td>
              <td>
                <% if @game.complete == true %>
                有
                <% else %>
                無
                <% end %>
              </td>
            </tr>
            <tr>
              <td>ゲームジャンル</td>
              <td><%= @game.genre.name %></td>
              <td></td>
              <td>周回プレイ要素</td>
              <td>
                <% if @game.orbit == true %>
                有
                <% else %>
                無
                <% end %>
              </td>
            </tr>
            <tr>
              <td>対応機種</td>
              <td>
                <% @models.each do |m| %>
                  <%= m.model.model %><br>
                <% end %>
              </td>
              <td></td>
              <td>マルチエンド方式</td>
              <td>
                <% if @game.multi_ending == true %>
                有
                <% else %>
                無
                <% end %>
              </td>
            </tr>
            <tr>
              <td>最大プレイ人数</td>
              <td><%= @game.number_of_people %>人</td>
              <td></td>
              <td>CEROレーティング</td>
              <td><%= @game.cero_rating %></td>
            </tr>
            <tr>
              <td>URL</td>
              <td colspan="4"><%= @game.site_url %></td>
            </tr>
            <tr>
            <td>内容</td>
              <td colspan="4"><%= @game.text %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12">
      <div class="admin-report-box">
          <h4><strong>通報内容</strong></h4>
          <div>通報理由
            <div class="report-details"><%= @report.reason %></div>
          </div>
          <div>通報内容詳細
            <div class="report-details"><%= @report.report %></div>
          </div>
          <div>ステータス
            <div class="report-details">
              <%= form_for([:admin,@report], html:{class: "form-inline"}) do |f| %>
              <%= @report.status %>
              <%= f.select :status, GameReport.statuses.keys.to_a, {include_blank: '選択'},class: "form-control" %>
              <%= f.submit "変更",class: "btn btn-primary" %>
              <% end %>
            </div>
          <div>対応内容
            <div class="report-details">
              <%= form_for([:admin,@report]) do |f| %>
              <%= @report.correspondence %>
              <%= f.text_area :correspondence,class: "form-control",placeholder: "入力" %>
              <%= f.submit "追加・変更",class: "btn btn-primary btn-block" %>
              <% end %>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>