config/routes.rb
Rails.application.routes.draw do

  get 'search/search'
  get 'search/search_page'
  namespace :admin do
    resources :members, only: [:index,:show, :edit, :update]
    get 'members/:id/comments' =>'members#comments', as: 'member_comments'
    get 'members/:id/games' =>'members#games', as: 'member_games'
    get 'members/:id/game_reports' =>'members#game_reports', as: 'member_game_reports'
    get 'members/:id/comment_reports' =>'members#comment_reports', as: 'member_comment_reports'
    resources :genres, only: [:index,:create, :update]
    resources :games, only: [:index,:show, :edit, :update,:destroy]
    resources :comments, only: [:destroy]
    resources :models, only: [:index,:create, :update]
    resources :game_reports, only: [:index,:show, :update]
    resources :comment_reports, only: [:index,:show, :update]
    resources :contacts, only: [:edit, :update, :index]
    post 'contacts/status_update' =>'contacts#status_update', as: 'contact_status_update'
    resources :warning_mails, only: [:new, :create, :show,:index]
    get 'search/search'
    get 'search/search_page'
  end
  get 'admin/top' => 'admin#top', as: 'admin_top'
  devise_for :admins, controllers: {
      sessions:      'admins/sessions',
      passwords:     'admins/passwords',
  }
  devise_for :members, controllers: {
  		sessions:      'members/sessions',
      passwords:     'members/passwords',
      registrations: 'members/registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'home#top'
  get 'home/about' => 'home#about'

  resources :members, only: [:show, :edit, :update]
  get 'members/:id/delete_me' => 'members#delete_me', as: 'delete_me'
  put 'members/:id/delete_me' =>'members#withdraw', as: 'withdraw'
  get 'members/:id/comments' =>'members#comments', as: 'my_comments'
  get 'members/:id/games' =>'members#games', as: 'my_games'
  get 'members/:id/favorites' =>'members#favorites', as: 'my_favorites'
  resources :game_reports, only: [:new, :create,:show]
  resources :comment_reports, only: [:new, :create,:show]
  resources :contacts, only: [:new, :create]

  resources :games, only: [:index, :show, :edit, :update, :create,:new] do
    resource :comments, only: [:create,:destroy]
    resource :favorites, only: [:create,:destroy]
  end
  put 'games/:id/hidden'      => 'games#hidden'     , as: 'hidden'
  post 'games/:id/playtime_create'      => 'games#playtime_create'
  get 'home/ranking' =>'home#ranking', as: 'ranking'


end

app/controllers/admin/search_controller.rb
class Admin::SearchController < AdminController
  def search
    title = params[:title]

    if params[:genre_ids] != nil
    genres = params[:genre_ids]
     genre_id = ""
     genres.each do |genre|
      genre_id = genre_id + genre
     end
    end

    if params[:model_ids] != nil
    models = params[:model_ids]
     model_id = ""
     models.each do |model|
      model_id = model_id + model
     end
    end

    if params[:complete] != nil
    complete = params[:complete]
    end
    if params[:orbit] != nil
    orbit = params[:orbit]
    end
    if params[:multi_ending] != nil
    multi_ending = params[:multi_ending]
    end

    if params[:cero_ratings] != nil
    cero_ratings = params[:cero_ratings]
     rating = ""
     cero_ratings.each do |cero_rating|
      rating = rating + cero_rating
     end
    end

    if title.present? #タイトル有
      @games = Game.where("title Like ?", "%#{params[:title]}%")
      if genre_id.present? #タイトル有、ジャンル有
        @games = Game.where("title Like ?", "%#{params[:title]}%")
                      .where(genre_id: genres)
        if model_id.present? #タイトル有、ジャンル有、対応機種有
          @games = Game.joins(:models)
                        .where("title Like ?", "%#{params[:title]}%")
                        .where(genre_id: genres)
                        .where(models: {id: models})
          if complete.present? #タイトル有、ジャンル有、対応機種有、コンプリート要素有
            @games = Game.joins(:models)
                          .where("title Like ?", "%#{params[:title]}%")
                          .where(genre_id: genres)
                          .where(models: {id: models})
                          .where(complete: complete)
            if orbit.present? #タイトル有、ジャンル有、対応機種有、コンプリート要素有、周回要素有
              @games = Game.joins(:models)
                            .where("title Like ?", "%#{params[:title]}%")
                            .where(genre_id: genres)
                            .where(models: {id: models})
                            .where(complete: complete)
                            .where(orbit: orbit)
              if multi_ending.present? #タイトル有、ジャンル有、対応機種有、コンプリート要素有、周回要素有、マルチエンド有
                @games = Game.joins(:models)
                              .where("title Like ?", "%#{params[:title]}%")
                              .where(genre_id: genres)
                              .where(models: {id: models})
                              .where(complete: complete)
                              .where(orbit: orbit)
                              .where(multi_ending: multi_ending)
                if rating.present? #タイトル有、ジャンル有、対応機種有、コンプリート要素有、周回要素有、マルチエンド有、CERO有
                  @games = Game.joins(:models)
                                .where("title Like ?", "%#{params[:title]}%")
                                .where(genre_id: genres)
                                .where(models: {id: models})
                                .where(complete: complete)
                                .where(orbit: orbit)
                                .where(multi_ending: multi_ending)
                                .where(cero_rating: cero_ratings)
                end
              else #タイトル有、ジャンル有、対応機種有、コンプリート要素有、周回要素有、マルチエンド無
                if rating.present? #タイトル有、ジャンル有、対応機種有、コンプリート要素有、周回要素有、マルチエンド無、CERO有
                  @games = Game.joins(:models)
                                .where("title Like ?", "%#{params[:title]}%")
                                .where(genre_id: genres)
                                .where(models: {id: models})
                                .where(complete: complete)
                                .where(orbit: orbit)
                                .where(cero_rating: cero_ratings)
                end
              end
            else #タイトル有、ジャンル有、対応機種有、コンプリート要素有、周回要素無
              if multi_ending.present? #タイトル有、ジャンル有、対応機種有、コンプリート要素有、周回要素無、マルチエンド有
                @games = Game.joins(:models)
                              .where("title Like ?", "%#{params[:title]}%")
                              .where(genre_id: genres)
                              .where(models: {id: models})
                              .where(complete: complete)
                              .where(multi_ending: multi_ending)
                if rating.present? #タイトル有、ジャンル有、対応機種有、コンプリート要素有、周回要素無、マルチエンド有、CERO有
                  @games = Game.joins(:models)
                                .where("title Like ?", "%#{params[:title]}%")
                                .where(genre_id: genres)
                                .where(models: {id: models})
                                .where(complete: complete)
                                .where(multi_ending: multi_ending)
                                .where(cero_rating: cero_ratings)
                end
              else #タイトル有、ジャンル有、対応機種有、コンプリート要素有、周回要素無、マルチエンド無
                if rating.present? #タイトル有、ジャンル有、対応機種有、コンプリート要素有、周回要素無、マルチエンド無、CERO有
                  @games = Game.joins(:models)
                                .where("title Like ?", "%#{params[:title]}%")
                                .where(genre_id: genres)
                                .where(models: {id: models})
                                .where(complete: complete)
                                .where(cero_rating: cero_ratings)
                end
              end
            end
          else #タイトル有、ジャンル有、対応機種有、コンプリート要素無
            if orbit.present? #タイトル有、ジャンル有、対応機種有、コンプリート要素無、周回要素有
              @games = Game.joins(:models)
                            .where("title Like ?", "%#{params[:title]}%")
                            .where(genre_id: genres)
                            .where(models: {id: models})
                            .where(orbit: orbit)
              if multi_ending.present? #タイトル有、ジャンル有、対応機種有、コンプリート要素無、周回要素有、マルチエンド有
                @games = Game.joins(:models)
                              .where("title Like ?", "%#{params[:title]}%")
                              .where(genre_id: genres)
                              .where(models: {id: models})
                              .where(orbit: orbit)
                              .where(multi_ending: multi_ending)
                if rating.present? #タイトル有、ジャンル有、対応機種有、コンプリート要素無、周回要素有、マルチエンド有、CERO有
                  @games = Game.joins(:models)
                                .where("title Like ?", "%#{params[:title]}%")
                                .where(genre_id: genres)
                                .where(models: {id: models})
                                .where(orbit: orbit)
                                .where(multi_ending: multi_ending)
                                .where(cero_rating: cero_ratings)
                end
              else #タイトル有、ジャンル有、対応機種有、コンプリート要素無、周回要素有、マルチエンド無
                if rating.present? #タイトル有、ジャンル有、対応機種有、コンプリート要素無、周回要素有、マルチエンド無、CERO有
                  @games = Game.joins(:models)
                                .where("title Like ?", "%#{params[:title]}%")
                                .where(genre_id: genres)
                                .where(models: {id: models})
                                .where(orbit: orbit)
                                .where(cero_rating: cero_ratings)
                end
              end
            else #タイトル有、ジャンル有、対応機種有、コンプリート要素無、周回要素無
              if multi_ending.present? #タイトル有、ジャンル有、対応機種有、コンプリート要素無、周回要素無、マルチエンド有
                @games = Game.joins(:models)
                              .where("title Like ?", "%#{params[:title]}%")
                              .where(genre_id: genres)
                              .where(models: {id: models})
                              .where(multi_ending: multi_ending)
                if rating.present? #タイトル有、ジャンル有、対応機種有、コンプリート要素無、周回要素無、マルチエンド有、CERO有
                  @games = Game.joins(:models)
                                .where("title Like ?", "%#{params[:title]}%")
                                .where(genre_id: genres)
                                .where(models: {id: models})
                                .where(multi_ending: multi_ending)
                                .where(cero_rating: cero_ratings)
                end
              else #タイトル有、ジャンル有、対応機種有、コンプリート要素無、周回要素無、マルチエンド無
                if rating.present? #タイトル有、ジャンル有、対応機種有、コンプリート要素無、周回要素無、マルチエンド無、CERO有
                  @games = Game.joins(:models)
                                .where("title Like ?", "%#{params[:title]}%")
                                .where(genre_id: genres)
                                .where(models: {id: models})
                                .where(cero_rating: cero_ratings)
                end
              end
            end
          end
        else #タイトル有、ジャンル有、対応機種無
          if complete.present? #タイトル有、ジャンル有、対応機種無、コンプリート要素有
            @games = Game.where("title Like ?", "%#{params[:title]}%")
                          .where(genre_id: genres)
                          .where(complete: complete)
            if orbit.present? #タイトル有、ジャンル有、対応機種無、コンプリート要素有、周回要素有
              @games = Game.where("title Like ?", "%#{params[:title]}%")
                            .where(genre_id: genres)
                            .where(complete: complete)
                            .where(orbit: orbit)
              if multi_ending.present? #タイトル有、ジャンル有、対応機種無、コンプリート要素有、周回要素有、マルチエンド有
                @games = Game.where("title Like ?", "%#{params[:title]}%")
                              .where(genre_id: genres)
                              .where(complete: complete)
                              .where(orbit: orbit)
                              .where(multi_ending: multi_ending)
                if rating.present? #タイトル有、ジャンル有、対応機種無、コンプリート要素有、周回要素有、マルチエンド有、CERO有
                  @games = Game.where("title Like ?", "%#{params[:title]}%")
                                .where(genre_id: genres)
                                .where(complete: complete)
                                .where(orbit: orbit)

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search
    title = params[:title]

    if params[:genre_ids] != nil
    genres = params[:genre_ids]
     genre_id = ""
     genres.each do |genre|
      genre_id = genre_id + genre
     end
    end

    if params[:model_ids] != nil
    models = params[:model_ids]
     model_id = ""
     models.each do |model|
      model_id = model_id + model
     end
    end

    if params[:complete] != nil
    complete = params[:complete]
    end
    if params[:orbit] != nil
    orbit = params[:orbit]
    end
    if params[:multi_ending] != nil
    multi_ending = params[:multi_ending]
    end

    if params[:cero_ratings] != nil
    cero_ratings = params[:cero_ratings]
     rating = ""
     cero_ratings.each do |cero_rating|
      rating = rating + cero_rating
     end
    end

    @games = Game.where(status: true)
    @games = @games.where("title Like ?", "%#{params[:title]}%") if title.present?
    @games = @games.where(genre_id: genres) if genre_id.present?
    @games = @games.joins(:models).where(models: {id: models}) if model_id.present?
    @games = @games.where(complete: complete) if complete.present?
    @games = @games.where(orbit: orbit) if orbit.present?
    @games = @games.where(multi_ending: multi_ending) if multi_ending.present?
    @games = @games.where(cero_rating: cero_ratings) if rating.present?
    @games = @games.page(params[:page]).per(10).reverse_order

  end

  def search_page
  end
end

app/helpers/admin/search_helper.rb
module Admin::SearchHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/admin/search/search.html.erb
<div class="row">
  <div class="col-xs-12">
    <h2 class="page-title" id="game-report">検索結果</h2>
    <%= link_to "詳細検索ページへ",admin_search_search_page_path,class: "btn btn-info" %>

    <div class="games">
      <table class= "table table-hover table-bordered table-admin">
        <thead>
          <tr>
            <th class="text-center">ゲームタイトル</th>
            <th class="text-center">ステータス</th>
            <th class="text-center">通報数</th>
            <th class="text-center">ジャンル</th>
            <th class="text-center">作成者</th>
            <th class="text-center">作成日</th>
            <th class="text-center">データ</th>
          </tr>
        </thead>
        <tbody>
          <% @games.each do |game| %>
            <tr class="text-center table-cel">
              <td><%= link_to game.title,admin_game_path(game.id) %></td>
              <td>
                <% if game.status == true %>
                <span class="label label-primary member-game-status">公開中</span>
              <% else %>
                <span class="label label-danger member-game-status">非公開</span>
              <% end%>
              </td>
              <td><%= game.game_reports.count %></td>
              <td><%= game.genre.name %></td>
              <td><%= link_to game.member.name,admin_member_path(game.member.id) %></td>
              <td><%= game.created_at.strftime("%Y/%m/%d") %></td>
              <td><span class="glyphicon glyphicon-heart"></span>
                 <%= game.favorites.count %>
                <span class="glyphicon glyphicon-comment"></span>
                 <%= game.comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="text-center"><%= paginate @games %></div>
  </div>
</div>

app/views/admin/search/search_page.html.erb
<div class="row">
  <div class="col-xs-12">
  <h2 class="page-title">管理者用詳細検索ページ</h2>
  </div>
</div>


<div class="admin-search-box">
  <div class="row">
    <div class="col-xs-12">
      <h4 class="text-center">絞り込みたい条件を入力・選択してください（一部空欄でも検索できます）</h4>
    </div>
  </div>
    <%= form_with(url: admin_search_search_path,method: :get,local: true) do |f| %>
  <div class="row search-item">
    <div class="col-xs-4">
      ゲームタイトル
    </div>
    <div class="col-xs-8">
      <%= f.text_field :title, placeholder: "入力",class: "form-control" %>
    </div>
  </div>
  <div class="row search-item">
    <div class="col-xs-4">
      ゲームジャンル（複数選択可）
    </div>
    <div class="col-xs-8">
      <%= f.collection_check_boxes :genre_ids, Genre.all, :id, :name %>
    </div>
  </div>
  <div class="row search-item">
    <div class="col-xs-4">
      対応機種（複数選択可）
    </div>
    <div class="col-xs-8">
      <%= f.collection_check_boxes :model_ids, Model.all.reverse_order, :id, :model %>
    </div>
  </div>
  <div class="row search-item">
    <div class="col-xs-4">
      コンプリート要素
    </div>
    <div class="col-xs-8">
        <label><%= f.radio_button :complete, true %>有</label>
        <label><%= f.radio_button :complete, false %>無</label>
    </div>
  </div>
  <div class="row search-item">
    <div class="col-xs-4">
      周回プレイ要素
    </div>
    <div class="col-xs-8">
        <label><%= f.radio_button :orbit, true %>有</label>
        <label><%= f.radio_button :orbit, false %>無</label>
    </div>
  </div>
  <div class="row search-item">
    <div class="col-xs-4">
      マルチエンド方式
    </div>
    <div class="col-xs-8">
        <label><%= f.radio_button :multi_ending, true %>有</label>
        <label><%= f.radio_button :multi_ending, false %>無</label>
    </div>
  </div>
  <div class="row search-item">
    <div class="col-xs-4">
      CEROレーティング
    </div>
    <div class="col-xs-8">
      <%= f.collection_check_boxes :cero_ratings, Game.cero_ratings, :first, :first %>
    </div>
    <div class="col-xs-12">
      <%= f.submit "検索",class: "btn btn-info btn-block" %>
    </div>
  </div>
    <% end %>
</div>